Bump mccabe in lower-constraints.txt
... to solve the following conflict detected in lower-constraints job.

ERROR: Cannot install hacking because these package versions have conflicting dependencies.

The conflict is caused by: 
    flake8 3.7.9 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.7.8 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.7.7 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.7.6 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.7.5 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.7.4 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.7.3 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.7.2 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.7.1 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.7.0 depends on mccabe<0.7.0 and >=0.6.0
    flake8 3.6.0 depends on mccabe<0.7.0 and >=0.6.0

Change-Id: I757ef4591d4ae386cfe71f268008efe251f05e86